[package]
name = "actor-x"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hollywood = { path = "../../../hollywood" }
system = { path = "../../system" }
pretty_env_logger = "0.4.0"
tokio = { version = "1", features = ["full"] }