version: "3.7"
services:

  hollywood:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    links: ["nats1"]
    depends_on: ["nats1"]
    command: "tail -f /dev/null"
    working_dir: /hollywood
    volumes:
      - ../:/hollywood

  nats1:
    image: nats
    ports:
      - "14222:4222"
      - "18222:8222"

  nats2:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats1:6222"
    depends_on: ["nats1"]

  nats3:
    image: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats1:6222"
    depends_on: ["nats1"]

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '9763:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
