# Define multiple systems
# by name and what nats uri they're
# back by...
[[system]]
name = "examples"
nats_uri = "nats://127.0.0.1:14222"

# Define an actor by name
[[actor]]
name = "ActorX"

# Define how to run an actor using hollywood-cli dev
[actor.dev]
bin = "actor-x"
path = "bin/actor-x"
env = ["RUST_LOG=info"]
watch = ["system", "../hollywood"]

[[actor]]
name = "ActorY"

[actor.dev]
bin = "actor-y"
path = "bin/actor-y"
env = ["RUST_LOG=info"]
watch = ["system", "../hollywood"]

[[actor]]
name = "ActorZ"

[actor.dev]
bin = "actor-z"
path = "bin/actor-z"
env = ["RUST_LOG=info"]
watch = ["system", "../hollywood"]

[[actor]]
name = "ActorZZ"

[actor.dev]
bin = "actor-zz"
path = "bin/actor-zz"
env = ["RUST_LOG=info"]
watch = ["system", "../hollywood"]